version: '3.7'

services:
  redis:
    image: redis:alpine
    container_name: redis

  postgres:
    image: postgres:17
    container_name: postgres
    env_file:
      - ./postgres/.env
    volumes:
      - ./postgres/init-db:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data:Z

  bookmark-service:
    image: hemlockpham/bookmark-service:latest
    restart: always
    container_name: bookmark-service
    depends_on:
      - redis
      - postgres
    env_file:
      - ./bookmark-service/.env
    volumes:
      - ./public.pem:/app/public.pem
      - ./private.pem:/app/private.pem

  worker-service:
    image: hemlockpham/worker-service:latest
    restart: always
    container_name: worker-service
    depends_on:
      - redis
      - postgres
    env_file:
      - ./worker-service/.env

  user-service:
    image: hemlockpham/user-service:latest
    restart: always
    container_name: user-service
    depends_on:
      - redis
      - postgres
    env_file:
      - ./user-service/.env
    volumes:
      - ./public.pem:/app/public.pem
      - ./private.pem:/app/private.pem

  nginx:
    image: nginx:alpine
    restart: always
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - bookmark-service
      - user-service
      - worker-service

networks:
  default:
    name: bookmark_management_network